version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_PASSWORD: 123
      MARIADB_USER: root
    ports:
      - 3306:3306
